### ISSUE TITLE
你好，遇见以下这两个问题怎么解决

### ISSUE THREAD

**Issue by huangxinrui** [liangdas/mqantserver#4]
1：go get github.com/liangdas/mqant-modules这个模块无法安装

2：在go install server下安装会出现这个错误

# server/xaxb/objects
src/server/xaxb/objects/player.go:46:23: this.BasePlayerImp.Session().GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
# server/chat
src/server/chat/RPCListener.go:30:12: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:64:2: undefined: "github.com/liangdas/mqant/log".TInfo
src/server/chat/module.go:65:12: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:73:2: undefined: "github.com/liangdas/mqant/log".TInfo
src/server/chat/module.go:78:45: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:89:19: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:94:24: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:101:10: user.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:101:33: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:106:29: user.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/chat/module.go:106:29: too many errors
# server/gate
src/server/gate/CustomAgent.go:110:22: this.GetSession().GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/gate/CustomAgent.go:116:62: this.GetSession().GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/gate/module.go:68:12: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
# server/login
src/server/login/module.go:74:2: undefined: "github.com/liangdas/mqant/log".TInfo
src/server/login/module.go:82:2: undefined: "github.com/liangdas/mqant/log".TInfo
src/server/login/module.go:93:2: undefined: "github.com/liangdas/mqant/log".TInfo
# server/hitball
src/server/hitball/module.go:68:12: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/hitball/table.go:241:35: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/hitball/table.go:252:15: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)
src/server/hitball/table.go:286:35: session.GetUserId undefined (type gate.Session has no field or method GetUserId, but does have GetUserid)

**Comment by liangdas** [comment]
更新一下mqant库
