### ISSUE TITLE
您好, 請問在測試robot時發生以下錯誤怎麼解決

### ISSUE THREAD

**Issue by JianLiu666** [liangdas/mqantserver#7]
2018-09-12T19:13:43+08:00 [-] [-] [development] [E] [rpc_server.go:263] RPC Exec ModuleType = Gate Func = SendBatch Elapsed = 0s ERROR:
The number of params [[51 99 100 56 48 52 97 53 48 49 102 101 50 101 50 102 44 55 55 100 49 53 50 98 57 52 98 102 57 50 55 57 98] [88 97 88 98 47 73 100 108 101] [123 34 67 111 105 110 34 58 53 48 48 125]] is not adapted.<func(log.TraceSpan, string, string, []uint8) (int64, string) Value>
github.com/liangdas/mqant/rpc/base/rpc_server.go:263
github.com/liangdas/mqant/rpc/base/rpc_server.go:297
github.com/liangdas/mqant/rpc/base/rpc_server.go:248

請問有大神知道為什麼嗎

**Comment by liangdas** [comment]
更新一下https://github.com/liangdas/mqant-modules库
